### ISSUE TITLE
Error restoring from storageEngine when passing component as breadcrumb (Safari only)

### ISSUE THREAD

**Issue by elverskog** [MrLeebo/redux-breadcrumb-trail#8]
Not sure if this qualifies as an issue (it's likely just an edge case). I was getting an error when trying to restore from localStorage. Loading "breadcrumb" back into store was causing the state to fail loading.

The error was that my "itemRenderer" for Breadcrumbs couldn't handle two things:

1. It didn't like children.props.children for some reason. It saw it as a keyed object that it couldn't render as children. So I had to recreate the <Link> manually using the children.props.children as the element content/text and children.props.to as "to".
2. I was passing a component as breadcrumb in a path (as oppose to a string). This worked in FF, Chrome and IE11. Said component was an SVG icon so it looks like that may not have been stored to localStorage properly in Safari. To solve I created a custom fallback for if the icon in my itemRenderer.

So I fixed it for with a workaround but hopefully this is of some value to you and the future of this lovely module.

**Comment by MrLeebo** [comment]
Thanks @elverskog for taking the time to write this up, 

1. Not sure I understand the first part. In the itemRenderer, `children` should be the breadcrumb component. I'd have to see what you're doing but it sounds like your breadcrumb component is getting passed into the children prop as an object, which React isn't going to be able to render.
2. Have you looked at https://github.com/MrLeebo/redux-breadcrumb-trail/blob/master/docs/ComponentCache.md ? It's an alternative way to declare breadcrumb components in a serializable way, which sounds like what you need (and in a roundabout way, this is probably what your workaround is doing)

**Comment by MrLeebo** [comment]
No response so I'm going to assume this is resolved.
