### ISSUE TITLE
Ignore some params instead of all of them

### ISSUE THREAD

**Issue by VinhVu0412** [MrLeebo/redux-breadcrumb-trail#9]
In my case, I have some paths like this 
- /category/:categoryId
- /category/:categoryId/:productId

I want to only ignore the `productId` param. It means that two paths **/category/1/1** and  **/category/1/2** are considered as the same. Moreover, I also want **/category/1/** to be treated as the same with  **/category/1/1**.
If I set ignoreParam on the product route to `true` then the `categoryId` also be ignored. So far, **/category/1** and **/category/2** now are the same and it does not what I looking for.

Is there any option for that? As far as I know, you haven't had it.

**Comment by MrLeebo** [comment]
Hi @VinhVu0412 ! Instead of `ignoreParams`, I think the option you're looking for is `useParentBreadcrumb` on the Product route:

```jsx
<Route path='category/:categoryId' component={Category} breadcrumb={CategoryBreadcrumb}>
  <Route path=':productId' component={Product} useParentBreadcrumb />
</Route>
```

Does that work?

**Comment by VinhVu0412** [comment]
We tried your solution but it doesn't work. **/category/1/1** and **/category/1/2** are treated as 2 differences. However, I want it to be as one.

According to the code below, the keys are the same, but unfortunately, the params are different. Therefore `matchBreadcrumb` function returns false.
 
```javascript
const matchBreadcrumb = other => {
  if (breadcrumb.breadcrumbKey !== other.breadcrumbKey) {
    return false
  }

  return isEqual(breadcrumb.params, other.params)
}
```

**Comment by MrLeebo** [comment]
What if you set the breadcrumb key to a static value?

```jsx
<Route path='category/:categoryId' component={Category} breadcrumb={CategoryBreadcrumb}>
  <Route path=':productId' breadcrumbKey='product' component={Product} useParentBreadcrumb />
</Route>
```

**Comment by MrLeebo** [comment]
I'll take silence to mean it worked.
